### ISSUE TITLE
Update to version 3.0

### ISSUE THREAD

**Issue by luzpaz** [OpenMandrivaAssociation/musescore#2]
https://github.com/musescore/MuseScore/releases/tag/v3.0

**Comment by luzpaz** [comment]
https://github.com/musescore/MuseScore/releases/tag/v3.0.2

**Comment by AngryPenguinPL** [comment]
Hi,
can you please report bugs, packages request or update request on https://issues.openmandriva.org

**Comment by luzpaz** [comment]
Done: https://issues.openmandriva.org/show_bug.cgi?id=2424
